# Site settings
title: RUCS
email: julia@cs.toronto.edu
description: "RUCS is a non-archival publication featuring the best of undergraduate computer science research at the University of Toronto."
baseurl: ""
url: "rucs.ca"
github_username:  rucs-uoft

# Build settings
markdown: kramdown
permalink: /:title
page-names: ["Submission Guidelines", "FAQ"]
post-categories: ["Artificial Intelligence", "Computational Biology", "Computer Vision", "Natural Language Processing", "Profiles and Interviews", "Software Engineering", "Software Projects", "Theory of Computation"]